export const ENDPOINTS = {
    hello: '/hello',
    user: '/user',
    profile: '/profile',
    logout: '/logout',
    modifyProfile: '/modifyProfile',
    reports: '/reportes',
    clientReportData: '/reporting/user/',
    userReportData: '/reporting/userdata',
    userDelete: '/reporting/user/',
    inventaryReport: '/reportes/inventarios',
    inventaryReportData: '/reporting/inventary/',
    saleReportData: '/reporting/sale/',
    login: '/login',
    logout: '/logout',
    addFAQ: '/agregar-pregunta',
    editFAQ: '/editar-pregunta/',
    deleteFAQ: '/',
    FAQS: '/faqs',
    email: '/correoElectronico',
    ordersYear:'reporting/ordersYears',
    economicReport:'reporting/economicReport',
    forget: '/forget-password',
    registerInventary:'/agregar-stock',
    points:'/points',
    discount: '/discount',
    registerProduct: '/create-product',
    creatcategory: '/create-category',
    getCategories: '/categories',
    getProduct: '/product/',
    getProducts: '/products',
    products:'/getProducts',    
    getProductP: '/productos/',
    editProduct: '/productos/',
    emailVerification: '/verify-email',
    emailResend: '/resend-email',
    promotionAndProduct:'promotions/product',
    promotionAndProducts:'promotions/products',
    saveSale:'compra/guardar',
    validar:'compra/validar',
    payment:'compra/payment',
    discounts: '/discounts',
    discount: '/discount',
    uploadProfileImage: '/upload-pimage',
    deleteProfileImage: '/delete-pimage',
    verifyAuthUser: '/verify-auth',
    updateProfile: '/updateProfile',
    dashboardOrders: '/reporting/orders/',
    dashboardExpenses: '/reporting/expensives/',
    dashboardUsers: '/reporting/users/',
    dashboardMostSelleds: '/reporting/mostSelleds/',
    dashboardIncomes: '/reporting/incomes/',
    restore:'/restore',
    //añadir todos los endpoints que se necesiten
}